# -*- coding: utf-8 -*-
"""reconhecimento_imagem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GQDisenwkslLEmp8J11ZnALvtJ-kpfGP
"""

import cv2
import mediapipe as mp

webcam = cv2.VideoCapture(0) #cria conexao com a webcan
reconhecimento_maos = mp.solutions.hands
desenho_mp = mp.solutions.drawing_utils
maos = reconhecimento_maos.Hands()
if webcam.isOpened():
    validacao, frame = webcam.read()
    while validacao:
        validacao, frame = webcam.read()
        frameRGB = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        lista_maos = maos.process(frameRGB)
        
        if lista_maos.multi_hand_landmarks:
            for mao in lista_maos.multi_hand_landmarks:
                legal = mao.landmark
                desenho_mp.draw_landmarks(frame, mao, reconhecimento_maos.HAND_CONNECTIONS)
        cv2.imshow('Video da webcam', frame) #mostra a webcan
        tecla = cv2.waitKey(2) #manda esperar um pouquinho
        if tecla == 27:
            break

webcam.release()
cv2.destroyAllWindows()

